IR_BackOffice/IR_BackOffice/Controllers/ManageTipsController.cs
using System;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using IR_BackOffice.Infrastructure;
using IR_BackOffice.Models;
using IR_BackOffice_Data;
using TipsItem = IR_BackOffice_Data.TipsItem;


namespace IR_BackOffice.Controllers
{
    public class ManageTipsController : Controller
    {
        //
        // GET: /ManageFreeBets/

        private readonly IBackOfficeDataSource _repsoitory = new IR_Database();
        [Authorize]
        public ActionResult Index()
        {
            var tipsItem = _repsoitory.TipsItems;
            return View(tipsItem);
        }

        [Authorize]
        public ActionResult Create()
        {
            var model = new CreateTipsViewModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateTipsViewModel input)
        {
            if (ModelState.IsValid)
            {
                WebImage image = null;

                try
                {
                    image = WebImage.GetImageFromRequest();
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine("Error uploading image: " + e.Message);
                }

                var tips = new TipsItem();

                if (image != null)
                {
                    byte[] toPutInDb = image.GetBytes();
                    tips.Image = toPutInDb;
                }

                tips.Title = input.Title;
                tips.Text = input.Text;
                tips.DateAdded = input.DateAdded;
                tips.IsLive = input.IsLive;

                var data = new IR_Database();
                data.TipsItems.Add(tips);
                data.SaveChanges();

                return View("Index", data.TipsItems);
            }

            return View(input);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            TipsItem n = _repsoitory.TipsItems.Single(u => u.Id == id);

            var model = new EditTipsViewModel
            {
                Id = n.Id,
                Title = n.Title,
                Text = n.Text,
                DateAdded = n.DateAdded,
                IsLive = n.IsLive
            };

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(EditTipsViewModel input)
        {
            if (ModelState.IsValid)
            {
                var data = new IR_Database();
                TipsItem n = data.TipsItems.Single(u => u.Id == input.Id);

                WebImage image = null;

                try
                {
                    image = WebImage.GetImageFromRequest();
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine("Error uploading image: " + e.Message);
                }

                if (image != null)
                {
                    byte[] toPutInDb = image.GetBytes();
                    n.Image = toPutInDb;
                }

                n.Title = input.Title;
                n.Text = input.Text;
                n.DateAdded = input.DateAdded;
                n.IsLive = n.IsLive;
                data.SaveChanges();

                return View("Index", data.TipsItems);
            }
            return View(input);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            var data = new IR_Database();
            TipsItem n = data.TipsItems.Single(u => u.Id == id);
            return View(n);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var data = new IR_Database();
            TipsItem n = data.TipsItems.Single(u => u.Id == id);
            data.TipsItems.Remove(n);
            data.SaveChanges();
            return View("Index", data.TipsItems);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            var data = new IR_Database();
            TipsItem n = data.TipsItems.Single(u => u.Id == id);
            return View(n);
        }
    }
}

IR_BackOffice/IR_BackOffice/Controllers/TipsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using IR_BackOffice.Infrastructure;
using IR_BackOffice_Data;

namespace IR_BackOffice.Controllers
{
    public class TipsController : Controller
    {
        private readonly IBackOfficeDataSource _repository = new IR_Database();

        public async Task<ActionResult> Index()
        {
            var allTipsItems =
               await
               Task.FromResult(_repository.TipsItems.OrderByDescending(u => u.DateAdded));

            return View(allTipsItems);
        }

        public async Task<ActionResult> Tips(int id)
        {
            var detailedTipItem = await Task.FromResult(_repository.TipsItems.Single(u => u.Id == id));
            return View(detailedTipItem);
        }

        public async Task<ActionResult> TipsMini()
        {
            var allTipsItems =
               await
               Task.FromResult(_repository.TipsItems.OrderByDescending(u => u.DateAdded).Take(4));

            return PartialView("_TipsFeed", allTipsItems);
        }

        public async Task<FileContentResult> DisplayImageAsync(int id)
        {
            var img = await Task.FromResult(_repository.TipsItems.Single(u => u.Id == id).Image);

            if (img == null)
            {
                byte[] trackingGif = { 0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x81, 0x00, 0x00, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0xff, 0x0b, 0x4e, 0x45, 0x54, 0x53, 0x43, 0x41, 0x50, 0x45, 0x32, 0x2e, 0x30, 0x03, 0x01, 0x01, 0x00, 0x00, 0x21, 0xf9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x08, 0x04, 0x00, 0x01, 0x04, 0x04, 0x00, 0x3b };
                img = trackingGif;
            }

            return File(img, "image/jpeg");
        }
    }
}

IR_BackOffice/IR_BackOffice/Views/ManageTips/Create.cshtml
@model IR_BackOffice.Models.CreateTipsViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "ManageTips", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CreateTipsViewModel</legend>

        <div>
            Title
        </div>
        <div>
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div>
            Image<br />
            <br />
            When uploading an image for Betting Tips, for best results use a .png image with a transparent background and size roughly: 80px x 80px (Square). For more information visit: <a href="http://www.w3.org/TR/PNG/" style="color: blue; text-decoration: underline">http://www.w3.org/TR/PNG/</a>
            <br />
            <br />
        </div>
        <input type="file" name="image" />

        <div>
            <br />
            Content
        </div>
        <div>
            @Html.EditorFor(model => model.Text)
            @Html.ValidationMessageFor(model => model.Text)
        </div>

        <div>
            <br />
            Date Added (dd/mm/yy)
            <br />
        </div>
        <div>
            @Html.EditorFor(model => model.DateAdded)
            @Html.ValidationMessageFor(model => model.DateAdded)
        </div>

        <div>
            Is Live?&nbsp;
            @Html.EditorFor(model => model.IsLive)
            @Html.ValidationMessageFor(model => model.IsLive)
            <br />
            <br />
        </div>
        <input type="submit" value="Create" />
    </fieldset>
}

<div>
    @Html.ActionLink("<< Back to List", "Index", null, new { @Style = "color: blue; text-decoration: underline;" })
    <br />
    <br />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IR_BackOffice/IR_BackOffice/Views/ManageTips/Delete.cshtml
@model IR_BackOffice_Data.TipsItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TipsItems</legend>

    <div>
        <b>@Html.DisplayNameFor(model => model.Title): </b>
    </div>
    <div>
        @Html.Raw(@Html.DisplayFor(model => model.Title))
    </div>
    <div>
        <b>@Html.DisplayNameFor(model => model.Text): </b>
    </div>
    <div>
        @Html.Raw(@Html.DisplayFor(model => model.Text))
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <br />
    <p>
        <input type="submit" value="Delete" />
        |
        @Html.ActionLink("Back to List", "Index", null, new { @Style = "color: blue; text-decoration: underline;" })
    </p>
}

IR_BackOffice/IR_BackOffice/Views/ManageTips/Details.cshtml
@model IR_BackOffice_Data.TipsItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>TipsItem</legend>

    <div>
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div>
        @Html.DisplayFor(model => model.Title)
    </div>

    <div>
         @Html.DisplayNameFor(model => model.Text)
    </div>
    <div>
        @Html.DisplayFor(model => model.Text)
    </div>

    <div>
         @Html.DisplayNameFor(model => model.DateAdded)
    </div>
    <div>
        @Html.DisplayFor(model => model.DateAdded)
    </div>

    <div>
         @Html.DisplayNameFor(model => model.IsLive)
    </div>
    <div>
        @Html.DisplayFor(model => model.IsLive)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IR_BackOffice/IR_BackOffice/Views/ManageTips/Edit.cshtml
@model IR_BackOffice.Models.EditTipsViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ManageTips", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EditTipsItem</legend>

        @Html.HiddenFor(model => model.Id)

        <table>
            <tr>
                <td style="vertical-align: middle;">
                    <div>
                        Title
                    </div>
                    <div>
                        @Html.EditorFor(model => model.Title)
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>

                    <div>
                        Image<br/><br/>
            When uploading an image for Betting Tips, for best results use a .png image with a transparent background and size roughly: 80px x 80px (Square). For more information visit: <a href="http://www.w3.org/TR/PNG/" style="color: blue; text-decoration: underline">http://www.w3.org/TR/PNG/</a>
            <br/><br />
                    </div>
                    <input type="file" name="image" />

                </td>
                <td style="vertical-align: middle;">
                    <img src="@Url.Action("DisplayImageAsync", "Tips", new { id = Model.Id })" />
                </td>
            </tr>
        </table>

        <div>
            <br />
            Context
        </div>
        <div>
            @Html.EditorFor(model => model.Text)
            @Html.ValidationMessageFor(model => model.Text)
        </div>

        <div>
            <br />
            Date Added
        </div>
        <div>
            @Html.EditorFor(model => model.DateAdded)
            @Html.ValidationMessageFor(model => model.DateAdded)
        </div>

        <div>
            Is Live?&nbsp;

            @Html.EditorFor(model => model.IsLive)
            @Html.ValidationMessageFor(model => model.IsLive)
        </div>
        <br />
        <input type="submit" value="Save" />

    </fieldset>
}

<div>
    @Html.ActionLink("<< Back to List", "Index", null, new { @Style = "color: blue; text-decoration: underline;" })
    <br />
    <br />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IR_BackOffice/IR_BackOffice/Views/ManageTips/Index.cshtml
@model IEnumerable<IR_BackOffice_Data.TipsItem>

@{
    ViewBag.Title = "Tips Items";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Tips Items</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @style = "color: blue; text-decoration: underline;" })
</p>
<table>
    <tr>
        <th style="text-align: center; padding: 0px 30px 0px 30px">Title</th>
        <th style="text-align: center; padding: 0px 30px 0px 30px">Content</th>
        <th style="text-align: center; padding: 0px 30px 0px 30px">Date Added</th>
        <th style="text-align: center; padding: 0px 30px 0px 30px">Is Live?</th>
        <th colspan="3">Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.DateAdded).ToString().Remove(8)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IsLive)
            </td>
            <td colspan="3" style="text-align: center;">
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>