IR_BackOffice/IR_BackOffice/Controllers/BookmakerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using IR_BackOffice.Infrastructure;
using IR_BackOffice_Data;

namespace IR_BackOffice.Controllers
{
    public class BookmakerController : Controller
    {
        private readonly IBackOfficeDataSource _repository = new IR_Database(); 

        public async Task<ActionResult> Index()
        {
            var allBookmakerItems =
               await
               Task.FromResult(_repository.BookmakerItems.OrderByDescending(u => u.DateAdded));

            return View(allBookmakerItems);
        }

        public async Task<ActionResult> Bookmaker(int id)
        {
            var detailedBookmakerItem = await Task.FromResult(_repository.BookmakerItems.Single(u => u.Id == id));
            return View(detailedBookmakerItem);
        }

        public async Task<FileContentResult> DisplayImageAsync(int id)
        {
            var img = await Task.FromResult(_repository.BookmakerItems.Single(u => u.Id == id).Image);

            if (img == null)
            {
                byte[] trackingGif = { 0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x81, 0x00, 0x00, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0xff, 0x0b, 0x4e, 0x45, 0x54, 0x53, 0x43, 0x41, 0x50, 0x45, 0x32, 0x2e, 0x30, 0x03, 0x01, 0x01, 0x00, 0x00, 0x21, 0xf9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x08, 0x04, 0x00, 0x01, 0x04, 0x04, 0x00, 0x3b };
                img = trackingGif;
            }

            return File(img, "image/jpeg");
        }
    }
}

IR_BackOffice/IR_BackOffice/Controllers/NewsController.cs
using System;
using System.Threading.Tasks;
using System.Web.UI.WebControls;
using System.Xml;
using IR_BackOffice.Infrastructure;
using IR_BackOffice_Data;
using System.Linq;
using System.Web.Mvc;

namespace IR_BackOffice.Controllers
{
    public class NewsController : AsyncController
    {
        private readonly IBackOfficeDataSource _repository = new IR_Database();

        public async Task<ActionResult> Index()
        {
            var allNewsItems =
                await
                Task.FromResult(_repository.NewsItems.OrderByDescending(u => u.DateAdded));

            return View(allNewsItems);
        }

        public async Task<ActionResult> NewsItem(int id)
        {
            var detailedNewsItem = await Task.FromResult(_repository.NewsItems.Single(u => u.Id == id));
            return View(detailedNewsItem);
        }

        public async Task<FileContentResult> DisplayImageAsync(int id)
        {
            var img = await Task.FromResult(_repository.NewsItems.Single(u => u.Id == id).Image);

            if (img == null)
            {
                byte[] trackingGif = { 0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x81, 0x00, 0x00, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0xff, 0x0b, 0x4e, 0x45, 0x54, 0x53, 0x43, 0x41, 0x50, 0x45, 0x32, 0x2e, 0x30, 0x03, 0x01, 0x01, 0x00, 0x00, 0x21, 0xf9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x08, 0x04, 0x00, 0x01, 0x04, 0x04, 0x00, 0x3b };
                img = trackingGif;
            }

            return File(img, "image/jpeg");
        }
    }
}

IR_BackOffice/IR_BackOffice/Controllers/TipsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using IR_BackOffice.Infrastructure;
using IR_BackOffice_Data;

namespace IR_BackOffice.Controllers
{
    public class TipsController : Controller
    {
        private readonly IBackOfficeDataSource _repository = new IR_Database();

        public async Task<ActionResult> Index()
        {
            var allTipsItems =
               await
               Task.FromResult(_repository.TipsItems.OrderByDescending(u => u.DateAdded));

            return View(allTipsItems);
        }

        public async Task<ActionResult> Tips(int id)
        {
            var detailedTipItem = await Task.FromResult(_repository.TipsItems.Single(u => u.Id == id));
            return View(detailedTipItem);
        }

        public async Task<ActionResult> TipsMini()
        {
            var allTipsItems =
               await
               Task.FromResult(_repository.TipsItems.OrderByDescending(u => u.DateAdded).Take(4));

            return PartialView("_TipsFeed", allTipsItems);
        }

        public async Task<FileContentResult> DisplayImageAsync(int id)
        {
            var img = await Task.FromResult(_repository.TipsItems.Single(u => u.Id == id).Image);

            if (img == null)
            {
                byte[] trackingGif = { 0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x81, 0x00, 0x00, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0xff, 0x0b, 0x4e, 0x45, 0x54, 0x53, 0x43, 0x41, 0x50, 0x45, 0x32, 0x2e, 0x30, 0x03, 0x01, 0x01, 0x00, 0x00, 0x21, 0xf9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x08, 0x04, 0x00, 0x01, 0x04, 0x04, 0x00, 0x3b };
                img = trackingGif;
            }

            return File(img, "image/jpeg");
        }
    }
}

IR_BackOffice/IR_BackOffice/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - FABA</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" initial-scale="1.0" />
    @*
        The Styles.Render() line ensures that the Bootstrap css files are included. 
        Include your own style sheet by doing  @Styles.Render("~/Content/Css") and strip out all of the css in the Site.css file
        The /Content/Bootstrap path is declared in BundleConfig.cs in App_Star t
        *@
    @Styles.Render("~/Content/Bootstrap")
    @Styles.Render("~/Content/css")
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")


</head>
<body onload="init()">

    @*
        This is the navigation bar. You can hide menu items by using hidden-phone/hidden-tablet classes like so:
        <li class="hidden-phone">@Html.ActionLink("Contact", "Contact", "Home")</li>
        *@

    <div class="navbar navbar-inverse" style="vertical-align: middle; background-color: #8bb839">
        <div class="navbar-inner admin" style="vertical-align: middle; background-color: #8bb839">
            <div class="container" style="vertical-align: middle; height: 40px;">
                <table style="height: 100%; vertical-align: middle; border: 0 none white;">
                    <tr style="height: 100%; vertical-align: middle; background-color: #8bb839; border: 0 none white;">
                        <td style="height: 100%; vertical-align: middle; background-color: #8bb839; border: 0 none white;">
                            <a id="simple-menu" href="#sidr" style="height: 100%; vertical-align: middle; background-color: #8bb839; border: 0 none white;">
                                <span style="font-size: 12pt; margin-left: 15px;">Toggle menu</span>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    @* 
        In here is where we set the layout of all our content. 
        So this example says we have a 2-8-2 layout with our main control being rendered in the span8.
        Look in Views/Home/Index.cshtml to see how that is laid out. 
        
        To hide any item you just need to use the class hidden-desktop/tablet/phone/print
        So to hide the far right span 2 give it the following markup: <div class="span2 hidden-phone">
        
        You can change this but the sum of the spans needs to equal 12. 

        *@
    <div id="sidr">
        <!-- Your content -->
        <ul>
            <li class="blueitem"><a href="~/bookmakers-admin/">Bookmakers</a></li>
            <li class="blueitem"><a href="~/news-admin">News Items</a></li>
            <li class="blueitem"><a href="~/tips-admin">Tips Items</a></li>
            <li class="blueitem"><a href="~/league-codes-admin">League Codes</a></li>

        </ul>
    </div>


    <div class="main span10" style="border: 4px solid #8bb839; padding-bottom: 20px; margin-bottom: 20px;">
        @RenderBody()
    </div>


    @*This Scripts.Render line adds in the Bootstrap Javascript into the page*@
    @*The path Script/Bootstrap is declared in the BundleConfig.cs in App_Start *@
    @Scripts.Render("~/Script/Bootstrap")
    @RenderSection("scripts", required: false)
    <script>

        function init() {
            $('#simple-menu').sidr();
            $.sidr('open', 'sidr');
        }
    </script>
</body>
</html>

IR_BackOffice/IR_BackOffice/Views/Shared/_BookmakerFeed.cshtml
@using IR_BackOffice.Models

<div id="divBookmakerFeed2" style="overflow-y: auto; background-color: white;" class="scroll">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.BookmakerItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive).Take(10);

            if (!items.Any())
            {
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no bookmaker items to display.</span>
        </div>  
            }
            else
            {
                int index = 1;
                int itemCount = items.Count();

                foreach (var item in items)
                {
        <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 10px">
            <table>
                <tr>
                    <td style="width: 105px; padding-right: 10px; text-align: left; vertical-align: middle;">
                        <img style="border: 0px none white; max-height: 40px; max-width: 100px;" src="@Url.Action("DisplayImageAsync", "Bookmaker", new { id = item.Id })" />
                    </td>
                    <td>
                        <span style="font-family: Gotham-Medium">@item.DateAdded.ToLongDateString()</span><br />
                        <a target="_blank" href="@item.Url"><span style="font-family: Gotham-Bold; color: white;">@item.Title.ToUpper()</span></a><br />
                        <span style="font-family: Gotham-Medium; color: black; font-size: 7pt;"><a target="_blank" href="@item.Url" style="color: black; text-decoration: none;">VIEW SITE ></a></span><br />
                    </td>
                </tr>
            </table>



        </div>

                    if (index != itemCount)
                    {
        <div style="background-color: white; height: 2px;">
        </div>
                    }

                    index++;
                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading bookmaker items. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_BookmakerFeedMain.cshtml
@using IR_BackOffice.Models
@using IR_BackOffice.Objects

<div id="divBookmakerFeedMain" style="overflow-y: auto; background-color: white;">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.BookmakerItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive).Take(10);

            if (!items.Any())
            {
        <div style="background-color: white; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no news items to display.</span>
        </div>  
            }
            else
            {
                <div style="height: 15px"></div>
                
                int index = 1;
                int itemCount = items.Count();

                foreach (var item in items)
                {
        <div style="background-color: white; line-height: 20px; padding: 5px 10px 5px 10px; margin-top: -10px;">
            <table>
                <tr style="vertical-align: middle;">
                    <td style="width: 180px; text-align: left;">
                        <img style="border: 0px none white; max-width: 150px; margin-right: 10px; margin-bottom: 6px;" src="@Url.Action("DisplayImageAsync", "Bookmaker", new { id = item.Id })" />
                    </td>
                    <td style="vertical-align: middle;" colspan="2">
                        <span style="font-family: Gotham-Medium; font-size: 11pt;">@item.DateAdded.ToLongDateString()</span><br />
                        <br />
                        <span style="font-family: Gotham-Bold; color: Black; font-size: 12pt;">@item.Title.ToUpper()</span><br />
                    </td>
                </tr>
                <tr>
                    <td style="vertical-align: middle;" colspan="2">
                        <br />
                        <span style="font-family: Gotham-Light; color: Black; font-size: 10pt;">@Html.Raw(@item.Text)</span>
                    </td>
                </tr>
            </table>
            <div style="text-align: right; margin-bottom: -20px; margin-top: -10px">
                <a target="_blank" href="@item.Url"><span style="text-align: right; font-family: Gotham-Medium">VISIT SITE</span></a>
            </div>

            <div class="hr"></div>
        </div>

                    if (index != itemCount)
                    {
        <div style="background-color: white; height: 2px;">
        </div>
                    }

                    index++;
                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: white; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading bookmaker items. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_NewsFeed.cshtml
@using IR_BackOffice.Models

<div id="divLatestNews2" style="overflow-y: auto; background-color: white;" class="scroll">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.NewsItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive).Take(10);

            if (!items.Any())
            {
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no news items to display.</span>
        </div>  
            }
            else
            {
                int index = 1;
                int itemCount = items.Count();

                foreach (var item in items)
                {
                    <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 10px">
                        <span style="font-family: Gotham-Medium">@item.DateAdded.ToLongDateString()</span><br />
                        

                        <span style="font-family: Gotham-Bold; color: white;">@Html.ActionLink(@item.Title.ToUpper(), "NewsItem", "Home", new { id = item.Id }, new {@style="font-family: Gotham-Bold; color: white;"})</span><br />
                        

                        <span>@item.ShortText</span>
                    </div>

                    if (index != itemCount)
                    {
                        <div style="background-color: white; height: 2px;">
                        </div>
                    }
                    
                    index++;
                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading new. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_NewsFeedMain.cshtml
@using IR_BackOffice.Models

<div style="overflow-y: auto; background-color: white;">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.NewsItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive).Take(10);

            if (!items.Any())
            {
        <div style="background-color: white; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no news items to display.</span>
        </div>  
            }
            else
            {


                foreach (var item in items)
                {
        <div style="background-color: white; line-height: 20px; padding: 5px 10px 5px 10px; margin-top: 5px;">
            <table>
                <tr style="vertical-align: middle;">
                    <td style="width: 220px; text-align: left;">
                        <img style="border: 0px none white; max-width: 220px; margin-right: 10px; margin-bottom: 6px;" src="@Url.Action("DisplayImage", "News", new { id = item.Id })" />
                    </td>
                    <td style="vertical-align: middle;" colspan="2">
                        <span style="font-family: Gotham-Medium; font-size: 11pt;">@item.DateAdded.ToLongDateString()</span><br />
                        <br />
                        <span style="font-family: Gotham-Bold; color: Black; font-size: 12pt;">@item.Title.ToUpper()</span><br />
                        <span>@item.ShortText</span>
                    </td>
                </tr>
            </table>
            <div style="text-align: right;  margin-bottom: -20px; margin-top:-10px">
                <br />
                <span>@Html.ActionLink("VIEW ARTICLE", "NewsItem", "Home", new { id = item.Id }, new {@style="font-family: Gotham-Medium;"})</span>
            </div>
            
            <div class="hr"></div>
        </div>

                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: white; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading new. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_NewsItem.cshtml
@using IR_BackOffice.Models

<div id="divLatestNewsItem">
    <img style="border: 0px none white; max-width: 350px; margin-top:15px; text-align: center;" src="@Url.Action("DisplayImage", "News", new { id = Model.Id })" />

    <div style="background-color: white; text-align: left; margin-top: 10px; font-family: Gotham-Medium">
        <br />
        @Model.ShortText
    </div>
    <div style="background-color: white; text-align: left; margin-top: 10px; font-family: Gotham-Light">
        <br />
        @Html.Raw(@Model.Text)
    </div>
    <div style="padding-bottom: 15px; padding-top: 15px; text-align: left;"><span style="font-family: Gotham-Medium; text-decoration: underline;">@Html.ActionLink("BACK TO LIST", "News", "Home", null, null)</span></div>
</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_TipsFeed.cshtml
@using IR_BackOffice.Models

<div id="divBetFeed2" style="min-height: 280px; height: 280px; overflow: auto; background-color: white;" class="scroll">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.TipsItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive).Take(3);

            if (!items.Any())
            {
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no betting tip items to display.</span>
        </div>  
            }
            else
            {
                int index = 1;
                int itemCount = items.Count();

                foreach (var item in items)
                {
        <table style="width: 100%; vertical-align: middle;">
            <tr style="width: 100%; vertical-align: middle;">
                <td style="width: 1%;">
                    <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 10px; width: 35px; height:42px">
                        &nbsp;
                    </div>
                </td>
                <td style="width: 100px;">
                    <img style="border: 0px none white; margin-left: -50px; padding-top: 5px; padding-bottom: 5px; margin-right: 50px; height: 80px; max-width: 80px;" src="@Url.Action("DisplayImageAsync", "Tips", new { id = item.Id })" />
                </td>
                <td>
                    <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 55px; margin-left: -120px;">
                        <span style="font-family: Gotham-Medium;">@item.DateAdded.ToLongDateString()</span><br />
                        <span style="font-family: Gotham-Bold; color: white;">@Html.ActionLink(@item.Title.ToUpper(), "TipsItem", "Home", new { id = item.Id }, new {@style="font-family: Gotham-Bold; color: white;"})</span><br />
                    </div>
                </td>
                <td style="vertical-align: middle; width: 1%;">

                    <div style="background-color: #3a3d3f; height: 50px; vertical-align: middle; display: table-cell; overflow: hidden;">
                        <span style="font-family: Gotham-Bold; color: white; vertical-align: middle;">@Html.ActionLink("VIEW", "TipsItem", "Home", new { id = item.Id }, new { @style = "font-family: Gotham-Bold; color: white; vertical-align: middle; padding-left: 10px; padding-right: 10px;" })</span>
                    </div>

                </td>
            </tr>
        </table>
        
                    if (index != itemCount)
                    {
        <div style="background-color: white; height: 2px;">
        </div>
                    }

                    index++;
                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: #8bb839; height: 95%; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading betting tip items. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_TipsFeedMain.cshtml
@using IR_BackOffice.Models

<div id="divBetFeedMain" style="background-color: white;">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.TipsItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive);

            if (!items.Any())
            {
        <div style="background-color: #8bb839; height: 95%; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no betting tip items to display.</span>
        </div>  
            }
            else
            {
                int index = 1;
                int itemCount = items.Count();

                foreach (var item in items)
                {
        <table style="width: 100%; vertical-align: middle;">
            <tr style="width: 100%; vertical-align: middle;">
                <td style="width: 1%;">
                    <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 10px; width: 35px; height: 40px;">
                        &nbsp;
                    </div>
                </td>
                <td style="width: 100px;">
                    <img style="border: 0px none white; margin-left: -50px; padding-top: 5px; padding-bottom: 5px; margin-right: 50px; height: 80px; max-width: 80px;" src="@Url.Action("DisplayImageAsync", "Tips", new { id = item.Id })" />
                </td>
                <td>
                    <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 55px; height: 40px; margin-left: -120px;">
                        <span style="font-family: Gotham-Medium">@item.DateAdded.ToLongDateString()</span><br />
                        <span style="font-family: Gotham-Bold; color: white;">@item.Title.ToUpper()</span><br />
                    </div>
                </td>
                <td style="vertical-align: middle; width: 110px; text-align: center;">
                    <a href="">
                        <div style="background-color: #3a3d3f; height: 50px; vertical-align: middle; display: table-cell; width: 110px;">
                            <span style="font-family: Gotham-Bold; color: white; vertical-align: middle;">@Html.ActionLink("VIEW TIP", "TipsItem", "Home", new { id = item.Id }, new { @style = "font-family: Gotham-Bold; color: white; vertical-align: middle; padding-left: 10px; padding-right: 10px;" })</span>
                        </div>
                    </a>
                </td>
            </tr>
        </table>
        
                    if (index != itemCount)
                    {
        <div style="background-color: white; height: 2px;">
        </div>
                    }

                    index++;
                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: white; height: 95%; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading betting tip items. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_TipsFeedMini.cshtml
@using IR_BackOffice.Models

<div id="divBetFeedMini" style="overflow-y: auto; background-color: white;" class="scroll">
    @{
        var db = new IR_BackOffice.Infrastructure.IR_Database();

        try
        {
            var items = db.TipsItems.OrderByDescending(u => u.DateAdded).Where(u => u.IsLive).Take(10);

            if (!items.Any())
            {
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">There are no betting tip items to display.</span>
        </div>  
            }
            else
            {
                int index = 1;
                int itemCount = items.Count();

                foreach (var item in items)
                {
        <div style="background-color: #8bb839; line-height: 20px; padding: 5px 10px 5px 10px">
            <table>
                <tr>
                    <td style="width: 75px; padding-right: 10px; text-align: center; vertical-align: middle;">
                        <img style="border: 0px none white; height: 75px; max-width: 75px;" src="@Url.Action("DisplayImageAsync", "Tips", new { id = item.Id })" />
                    </td>
                    <td>
                        <span style="font-family: Gotham-Medium">@item.DateAdded.ToLongDateString()</span><br />
                        <span style="font-family: Gotham-Bold; color: white;">@Html.ActionLink(@item.Title.ToUpper(), "TipsItem", "Home", new { id = item.Id }, new {@style="font-family: Gotham-Bold; color: white;"})</span><br />
                        <span style="font-family: Gotham-Medium; color: black; font-size: 7pt;">@Html.ActionLink("VIEW TIP >", "TipsItem", "Home", new { id = item.Id }, new {@style="font-family: Gotham-Medium;"})</span><br />
                    </td>
                </tr>
            </table>



        </div>

                    if (index != itemCount)
                    {
        <div style="background-color: white; height: 2px;">
        </div>
                    }

                    index++;
                }
            }
        }
        catch (Exception e)
        {
            Console.Out.WriteLine("Error: " + e.Message);
            
        <div style="background-color: #8bb839; padding: 10px 10px 10px 10px;">
            <span style="font-family: Gotham-Medium; color: black;">Error loading betting tip items. Please try again later.</span>
        </div>  
        }
    }

</div>

IR_BackOffice/IR_BackOffice/Views/Shared/_TipsItem.cshtml
@using IR_BackOffice.Models

<div id="divTipsItem">
    <img style="border: 0px none white; max-width: 350px; margin-top:15px; text-align: center;" src="@Url.Action("DisplayImageAsync", "Tips", new { id = Model.Id })" />

    <div style="background-color: white; text-align: left; margin-top: 10px; font-family: Gotham-Light">
        <br />
        @Html.Raw(@Model.Text)
    </div>
    <div style="padding-bottom: 15px; padding-top: 15px; text-align: left;"><span style="font-family: Gotham-Medium; text-decoration: underline;">@Html.ActionLink("BACK TO LIST", "Tips", "Home", null, null)</span></div>
</div>